version: '1.0'

services:
  db:
    image: mysql:8.0
    container_name: user_registration_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_registration
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: user-registration-app
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: user_registration
      DB_HOST: db
      DB_PORT: 3306
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: